### PR TITLE
Added rust favicon

### PR DESCRIPTION
**Pull request by sntdevco**
## Description
It's inevitable to avoid this statement, but I just love Rust, and you can't take that away from me. Well then why leave it's icon! This PR adds the favicon to the Async Tracking Page

`// waiting for CI checks`

### CODE REVIEW

**Comment by upsuper** [comment]
Thanks.

**Comment by sntdevco** [comment]
> Thanks.

Nope, it won't work like this, the favicon is still not appearing

**Comment by upsuper** [comment]
Oh, wrong directory... will fix

**Comment by sntdevco** [comment]
> Oh, wrong directory... will fix

The Pages is hosted to go with which `dir` as the root?

**Comment by upsuper** [comment]
Files under `static` are copied into the output, and templates are just used to generate the main page.

**Comment by sntdevco** [comment]
> Files under `static` are copied into the output, and templates are just used to generate the main page.

Fine, I'll fix that. Thanks @upsuper

**Comment by upsuper** [comment]
I have fixed that in master.

**Comment by sntdevco** [comment]
Great. Thanks

**Comment by sntdevco** [comment]
Yes it works!

**Pull request merged**
